#language: java
#
#jdk:
#- oraclejdk8
#
#script:
#  - mvn -q clean install -Pno-network
#  - jdk_switcher use openjdk7
#  - cd core
#  - mvn -q clean package -Pno-network
#
#after_success:
#  - cd ../core
#  - mvn jacoco:report coveralls:report
#
